spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: luozhikun@@123
    url: jdbc:mysql://192.168.141.70:3306/user?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&autoReconnect=true&&zeroDateTimeBehavior=convertToNull&useSSL=true&allowMulQueries=true&&nullCatalogMeansCurrent=true

logging:
  level:
    org.invoice.cloud.dao: debug

u:
  name: user
  age: 18